apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: dusty1
  name: blazor-web-ingress
  annotations:
    cert-manager.io/cluster-issuer: cert-manager-webhook-duckdns-dusty-production
spec:
  tls:
    - hosts:
      - dusty-second.duckdns.org
      secretName: dusty-kube-tls-production
  ingressClassName: nginx
  rules:
  - host: dusty-second.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: blazor-web-service
            port:
              number: 80
              