{
 "title": "Grafana Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Number of Created Tickets Last 10 minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(CreateTicketObserver[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Tickets Created over Time",
   "type": "timeseries",
   "description": "Uses Time Series",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time( CreateTicketObserver[1d])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(1, MyHistogram_bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load time for Scanning a Ticket (ms)",
   "type": "barchart",
   "description": "Shows the distribution of a random number generated in Events Get All Service.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(MyHistogram_bucket{job=\"metrics_collector\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proportion of Tickets Unscanned",
   "type": "gauge",
   "description": "This is the proportion of tickets that are in the system and that are not scanned.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(NumberOfUnscannedTickets / CreateTicketObserver) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}