{
 "title": "Monitoring Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "alleventscallcount", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of Home Page Hits",
   "type": "timeseries",
   "description": "Observable Gauge ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "Gauge", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Histogram",
   "type": "histogram",
   "description": "Record Get All in ApiTicketService",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "MyHistogram_bucket", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of Unscanned Tickets",
   "type": "timeseries",
   "description": "Observable Up Down Counter",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "NumberOfUnscannedTickets", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Create Ticket Observer",
   "type": "timeseries",
   "description": "This is an Observable Counter in Api Ticket Service",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "CreateTicketObserver", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of Up Clicks",
   "type": "timeseries",
   "description": "This is a Up Down Counter Metric (home.razor)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "UpAndDownCounter" }
   ]
  }
 ]
}