{
 "title": "Structured Logging",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Adding a Ticket",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{exporter=\"OTLP\"} | json | line_format \"{{.body}}\" |~ \".Add Ticket.*\""
    }
   ]
  },
  {
   "title": "Getting All Tickets",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{exporter=\"OTLP\"} | json | line_format \"{{.body}}\" |~ \".*All Tickets.*\""
    }
   ]
  },
  {
   "title": "Get Single Event",
   "type": "table",
   "description": "Logs when the ApiEventService is called getting a singular event.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{exporter=\"OTLP\"} | json | line_format \"{{.body}}\" |~ \".*Single Event.*\""
    }
   ]
  },
  {
   "title": "Sending Email",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{exporter=\"OTLP\"} | json | line_format \"{{.body}}\" |~ \".*Email.*\""
    }
   ]
  },
  {
   "title": "Get All Events Logs",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{exporter=\"OTLP\"} | json | line_format \"{{.body}}\" |~ \".*All Events.*\""
    }
   ]
  }
 ]
}