name: DS Backup Database
on:
    - workflow_dispatch
jobs:
    backup:
        runs-on: self-hosted
        steps:
            - name: Do a BIG Dumpy 💩
              run: |
                CONTAINER_NAME=$(kubectl -n dusty1 get pods --no-headers -o custom-columns=":metadata.name" | grep "blazor-web-db-deployment")
                kubectl -n dusty1 exec -t $CONTAINER_NAME -- \
                    pg_dumpall -c -U postgres > /MobileApp/dump.sql