name: Dustys Github Action Workflow
run-name: ${{ github.event.head_commit.message }} - Dusty's Gitub Action Workflow 🛸
on: [push]
jobs:
  Dusty-Deploy-Pipeline:
    runs-on: dusty
    steps:
      # - uses: actions/checkout@v4
      # - name: See where I'm at
      #   run: |
      #     ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'
      - name: Docker compose down first
        run: |
          pwd
          cd ./tickets-r-us-dusty/MobileApp/dscompose
          docker compose down -v

      - name: Remove old stuff?
        run: rm -rf ./tickets-r-us-dusty/ 

      - name: Check out repository code
        run: |
          git clone "https://${{ secrets.DUSTYS_THIRD_GITHUB_SECRET }}@github.com/dustyshaw/tickets-r-us-dusty"
          ls -a

      - name: Docker Compose Up
        run: |
          cd ./tickets-r-us-dusty/MobileApp/dscompose
          ls -a
          docker compose up --build -d 

      # - name: Linting
      #   run: |
      #     cd ./tickets-r-us-dusty/MobileApp/
      #     dotnet format --verify-no-changes --severity warn

      # - name: Warn as Errors when Building
      #   run: |
      #     cd ./tickets-r-us-dusty/MobileApp/
      #     dotnet build --warnaserror

      - name: Kubethings
        run: |
          cd ./tickets-r-us-dusty/MobileApp/
          docker build -t 144.17.92.12:5000/dusty/blazor-web:$GITHUB_RUN_ID .
          docker push 144.17.92.12:5000/dusty/blazor-web:$GITHUB_RUN_ID
          

          kubectl -n dusty1 delete configmap blazor-web-postgres-init || true
          kubectl -n dusty1 create configmap blazor-web-postgres-init --from-file=TestsRUS/20240212.07.58.45.sql
          
          kubectl -n dusty1 delete configmap dashboards || true
          kubectl -n dusty1 create configmap dashboards --from-file=dashboards.yml

          cd ./kube-config
          kubectl -n dusty1 delete configmap otel-config || true
          kubectl -n dusty1 create configmap otel-config --from-file=otel-collector-config.yml

          kubectl -n dusty1 delete configmap grafana-datasource-config || true
          kubectl -n dusty1 create configmap grafana-datasource-config --from-file=grafana-datasource.yml

          cd ..
          
          # kubectl apply -f kube/

          export RUN_ID=${{ github.run_id }}

          for file in ./kube/*; do
            # Apply the file using kubectl
            echo "------------------------------------------ APPLYING $file"
            cat $file | envsubst | kubectl apply -f -
          done

      # - name: Integration Tests
      #   run: |
      #     cd ./tickets-r-us-dusty/MobileApp/TestsRUS/
      #     dotnet test   

      # - name: Unit Tests
      #   run: |
      #     cd ./tickets-r-us-dusty/MobileApp/UnitTestsRUs/
      #     dotnet test
          
      - name: Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        if: always()
        with:
          webhook_url: ${{ secrets.DUSTYS_WEBHOOK }}
          needs: ${{ toJson(needs) }}
          job: ${{ toJson(job) }}
          steps: ${{ toJson(steps) }}
          overwrite: "{title: `Dusty pushed to github ${workflow_link}`}"
