name: PR Action Workflow
run-name: PULL REQUEST
on:
    pull_request:
        types: [opened, reopened]
jobs:
  deploy-to-kubernetes:
    runs-on: dusty
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: deploy kube environment
        run: |
            
            export PULL_REQUEST_ID=${{ github.event.pull_request.id }}
            export NAMESPACE="dusty-pr-$PULL_REQUEST_ID"

            kubectl create namespace $NAMESPACE || true
            
            kubectl -n $NAMESPACE delete configmap blazor-web-postgres-init || true
            kubectl -n $NAMESPACE create configmap blazor-web-postgres-init --from-file=MobileApp/TestsRUS/20240212.07.58.45.sql

            export RUN_SALT="pr-${PULL_REQUEST_ID}-${GITHUB_RUN_ID}"
            docker build -t 144.17.92.12:5000/dusty/blazor-web:pr-$RUN_SALT .
            docker push -t 144.17.92.12:5000/dusty/blazor-web:pr-$RUN_SALT

            for file in ./kube/*; do
                # Apply the file using kubectl
                echo "------------------------------------------ APPLYING $file"
                cat $file | envsubst | kubectl apply -f -
            done  
          