name: PR Action Workflow
run-name: PULL REQUEST
on:
    pull_request:
        types: [opened, reopened]
jobs:
  deploy-to-kubernetes:
    runs-on: dusty
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: deploy kube environment
        run: |
            export PULL_REQUEST_ID=${{ github.event.pull_request.id }}

            kubectl create namespace dusty-pr-$PULL_REQUEST_ID

            kubectl -n dusty-pr-$PULL_REQUEST_ID delete configmap blazor-web-postgres-init || true
            kubectl -n dusty-pr-$PULL_REQUEST_ID create configmap blazor-web-postgres-init --from-file=TestsRUS/20240212.07.58.45.sql

    
          